create table appointment (
    id bigint generated by default as identity,
    date timestamp,
    company_id bigint,
    note varchar(255),
    status varchar(255),
    primary key (id)
);

create table company (
    id bigint generated by default as identity,
    name varchar(255),
    location_id bigint,
    url varchar(255),
    contact_person_id bigint,
    primary key (id)
);

create table location (
    id bigint generated by default as identity,
    street varchar(255),
    house_number varchar(255),
    residence varchar(255),
    postal_code varchar(255),
    primary key (id)
);

create table person (
    id bigint generated by default as identity,
    first_name varchar(255),
    last_name varchar(255),
    email varchar(255),
    phone_number varchar(255),
    salutation varchar(255),
    primary key (id)
);
alter table appointment add constraint FKkitlquw475ct47brwaiiry5lt foreign key (company_id) references company;
alter table company add constraint FKihsmur30jfenddysvhg5xnym2 foreign key (contact_person_id) references person;
alter table company add constraint FK2fb6ricytdnmf83vedni0gqy4 foreign key (location_id) references location;
